spring:
  application:
    name: spring-aws

cloud:
  aws:
    credentials:
      profile-name: sasha
    region:
      static: us-east-2
      auto: false
    stack:
      auto: false # Automatic stack detection
custom:
  bucket-name:springexamplebucket